[project]
name = "verge_auth_sdk"
version = "0.0.13"
description = "Plug-and-play centralized authentication SDK for FastAPI microservices"
readme = "README.md"
keywords = ["fastapi", "authentication", "sdk", "microservices", "rbac", "jwt"]
license = { text = "MIT" }

authors = [
    { name = "Verge Infosoft", email = "contactus@vergeinfosoft.com" }
]

requires-python = ">=3.9"

dependencies = [
    "fastapi",
    "httpx",
    "python-dotenv"
]

[project.urls]
Homepage = "https://vergeinfosoft.com"
Documentation = "https://vergeinfosoft.com"
Source = "https://github.com/verge-infosoft/verge-auth"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
