[project]
name = "verge-auth-sdk"
version = "0.1.5"
description = "Secure centralized authentication SDK for FastAPI microservices"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

authors = [
    { name = "Verge Infosoft", email = "contactus@vergeinfosoft.com" }
]

dependencies = [
    "fastapi",
    "httpx",
    "python-dotenv"
]

[project.urls]
Homepage = "https://www.vergeinfosoft.com"

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "Cython>=3.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["verge_auth_sdk"]

[tool.setuptools.extension]
middleware = { sources = ["verge_auth_sdk/middleware.py"] }
secret_provider = { sources = ["verge_auth_sdk/secret_provider.py"] }
verge_routes = { sources = ["verge_auth_sdk/verge_routes.py"] }
